import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
	getSemester();
	return (
		<div className={(styles.container, styles.gradient)}>
			<Head>
				<title>Computer Science Club</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/club.png" />
			</Head>

			<main className={styles.main}>
				<Image
					src="/club.png"
					alt="Club's Logo with gradient"
					width={100}
					height={100}
				/>
				<h1 className={styles.title}>Computer Science Club</h1>

				<p className={styles.description}>
					A community of undergrads at Stan State aiming to foster and
					cultivate technical interest in the Central Valley.
				</p>
				<Link href="" id="about">
					<a className={styles.ghost_button}>Join Now</a>
				</Link>

				
			</main>

			<section className={styles.about}>
				<h1 className={styles.title}>About</h1>
				<div className={styles.grid}>
					<a
						href="https://ggiande.notion.site/ggiande/Computer-Science-Club-29e1663fd608474b863cef6ee942ab23"
						target="_blank"
						className={styles.card}
					>
						<h2>Workshops &#128296; </h2>
						<p>
							Check out some of our past and current workshops for
							the semester!
						</p>
					</a>

					<a
						href="https://discord.gg/JwsG64ByRn"
						target="_blank"
						className={styles.card}
					>
						<h2>Mentorships &#128119; </h2>
						<p>
							Surround yourself with individuals who can
							facilitate the learning process. Our community gives
							back by helping out others with mentorships and
							coaching. To quickly find yourself a new mentor,
							head on over to our discord and check out the
							<code> #mentorhsip</code> channel
						</p>
					</a>

					<a
						href="https://discord.gg/JwsG64ByRn"
						target="_blank"
						className={styles.card}
					>
						<h2>Internships &#128270; </h2>
						<p>
							Apply to internships. We help build your
							professional network and prepare you for employment.
							To quickly find some of our current resources, head
							on over to our discord and check out the{" "}
							<code> Career Development Category</code>.
						</p>
					</a>

					<a href="" target="_blank" className={styles.card}>
						<h2>Guest Speakers &#128226; </h2>
						<p>
							Gain insight from professionals in the industry.
							Developers will hold talks on/off campus to discuss
							their experience and help others succeed.
						</p>
					</a>

					<a
						href="https://discord.gg/JwsG64ByRn"
						className={styles.card}
						target="_blank"
					>
						<h2>Meetings &#128119; </h2>
						<p>
							We have started to meet in person! If you are
							interested in joining us and meeting new people,
							checkout the <code> #announcements</code> channel on
							the discord server.
						</p>
					</a>

					<a
						href="https://discord.gg/JwsG64ByRn"
						className={styles.card}
						target="_blank"
					>
						<h2>Hackathons &#128187; </h2>
						<p>
							Build and create an application at our annual
							hackathon. Employ the technical skills that you've
							learned here! Currently, none are scheduled ;-;
						</p>
					</a>
				</div>
			</section>

			<section className={styles.officers}>
				<h1 className={styles.title}>
					{getSemester()} {getCurrentYear()} Club Officers
				</h1>
				<div className={styles.grid}>
					{/* Giancarlo */}
					<div className={styles.officers_card}>
						<Image src="/gian.png" width={300} height={400}></Image>
						<h2>Giancarlo Garcia Deleon</h2>
						<h4>Vice President</h4>
						<p>
							Giancarlo is the Vice President of the Computer
							Science Club with a load of experience under his
							belt as well as a desire to help others find their
							path. Main maintainer of the Discord server and
							developer of this site.
						</p>
						<a
							className={styles.ghost_button}
							href="https://www.linkedin.com/in/giancarlo-garcia/"
							target="_blank"
						>
							LinkedIn &#8594;
						</a>
					</div>
				</div>
			</section>

			<footer className={styles.footer}>
				<strong>
					&copy; Stan State Computer Science Club {getCurrentYear()}{" "}
				</strong>
			</footer>
		</div>
	);
}

function getCurrentYear() {
	return new Date().getFullYear();
}

function getSemester() {
	const currentMonthNum = new Date().getMonth();
	return currentMonthNum + 1 <= 5 ? "Spring" : "Fall";
}
