import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={(styles.container, styles.gradient)}>
      <Head>
        <title>Computer Science Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/club.png" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/club_meeting.png"
          alt="Club's Meeting"
          width={1920}
          height={1080}
        />
        <Image
          src="/club.png"
          alt="Club's Logo with gradient"
          width={100}
          height={100}
        />
        <h1 className={styles.title}>Computer Science Club</h1>

        <p className={styles.description}>
          A community of undergrads at Stan State aiming to foster and cultivate
          technical interest in the Central Valley.
        </p>
        <a className={styles.ghost_button}>Join!</a>
      </main>

      <footer className={styles.footer}>
        <a>
          The opinions expressed on this website are the club's own and do not
          reflect the views of California State University, Stanislaus.
        </a>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
